-- GymFlex seed data - Men's Gym Wear

INSERT INTO categories (id, name, slug, description, sort_order) VALUES
('mens', "Men's", 'mens', 'Premium gym wear for men - built for performance.', 0)
ON CONFLICT(id) DO NOTHING;

INSERT INTO products (id, category_id, name, slug, description, price, sale_price, on_sale, is_active, is_featured, sort_order) VALUES
('gymflex-dri-fit-tee', 'mens', 'Dri-Fit Training Tee', 'dri-fit-training-tee', 'Moisture-wicking performance tee designed for intense workouts. Lightweight, breathable, and built to move.', 1499, NULL, 0, 1, 1, 0),
('gymflex-compression-tank', 'mens', 'Compression Tank Top', 'compression-tank-top', 'Sleeveless compression tank for maximum mobility. Sweat-wicking fabric keeps you dry through your toughest sets.', 1799, 1499, 1, 1, 1, 1),
('gymflex-joggers', 'mens', 'Performance Joggers', 'performance-joggers', 'Slim-fit training joggers with zippered pockets. Stretch fabric allows full range of motion for squats and lunges.', 2499, NULL, 0, 1, 1, 2),
('gymflex-stringer', 'mens', 'Classic Stringer Vest', 'classic-stringer-vest', 'Bodybuilding-style stringer vest for maximum shoulder freedom. Premium cotton blend with reinforced seams.', 1299, 999, 1, 1, 1, 3),
('gymflex-shorts', 'mens', 'Training Shorts', 'training-shorts', 'Lightweight 7-inch training shorts with built-in liner. Phone pocket and moisture-wicking fabric.', 1599, NULL, 0, 1, 0, 4),
('gymflex-hoodie', 'mens', 'Gym Hoodie', 'gym-hoodie', 'Oversized fit hoodie with kangaroo pocket. French terry fabric for warmth without weight.', 2999, 2499, 1, 1, 1, 5),
('gymflex-track-pants', 'mens', 'Track Pants', 'track-pants', 'Tapered track pants with ankle zippers. Water-resistant exterior with soft brushed interior.', 2199, NULL, 0, 1, 0, 6),
('gymflex-singlet', 'mens', 'Wrestling Singlet', 'wrestling-singlet', 'Compression singlet for wrestling and grappling. Four-way stretch fabric with flatlock stitching.', 3499, NULL, 0, 1, 0, 7),
('gymflex-cargo-joggers', 'mens', 'Cargo Joggers', 'cargo-joggers', 'Cargo joggers with 6 pockets. Tapered fit with elastic cuffs and adjustable waistband.', 2699, NULL, 0, 1, 0, 8),
('gymflex-racerback', 'mens', 'Racerback Gym Tee', 'racerback-gym-tee', 'Racerback cut tee for enhanced shoulder mobility. Anti-odor technology keeps you fresh.', 1699, 1399, 1, 1, 1, 9),
('gymflex-sleeveless-hoodie', 'mens', 'Sleeveless Hoodie', 'sleeveless-hoodie', 'Cut-off sleeveless hoodie for layered looks. Oversized fit with front pouch pocket.', 2199, NULL, 0, 1, 0, 10),
('gymflex-thermal-tee', 'mens', 'Thermal Long Sleeve', 'thermal-long-sleeve', 'Compression thermal tee for cold weather training. Brushed interior traps heat while wicking sweat.', 1899, NULL, 0, 1, 0, 11),
('gymflex-5inch-shorts', 'mens', '5 Inch Running Shorts', '5-inch-running-shorts', 'Lightweight 5-inch shorts with side splits. Built-in brief liner and zippered back pocket.', 1399, NULL, 0, 1, 0, 12),
('gymflex-zip-hoodie', 'mens', 'Full Zip Hoodie', 'full-zip-hoodie', 'Full zip hoodie with stand-up collar. Zippered pockets and thumbhole cuffs.', 3299, 2799, 1, 1, 0, 13),
('gymflex-muscle-tee', 'mens', 'Muscle Fit Tee', 'muscle-fit-tee', 'Slim-fit muscle tee with short sleeves. Contoured cut shows off your hard work.', 1199, NULL, 0, 1, 0, 14),
('gymflex-compression-leggings', 'mens', 'Compression Leggings', 'compression-leggings', 'Full-length compression tights for recovery and training. Graduated compression improves blood flow.', 1999, NULL, 0, 1, 0, 15),
('gymflex-polo', 'mens', 'Performance Polo', 'performance-polo', 'Athletic-fit polo for gym-to-street style. Moisture-wicking pique fabric with UPF 50+ protection.', 1999, NULL, 0, 1, 0, 16),
('gymflex-tank-top', 'mens', 'Sleeveless Gym Tank', 'sleeveless-gym-tank', 'Wide-strap sleeveless tank for heavy shoulder days. Drop armholes for unrestricted movement.', 1099, NULL, 0, 1, 0, 17),
('gymflex-windbreaker', 'mens', 'Lightweight Windbreaker', 'lightweight-windbreaker', 'Packable windbreaker jacket for outdoor training. Water-resistant with reflective details.', 3799, NULL, 0, 1, 0, 18),
('gymflex-beanie', 'mens', 'Gym Flex Beanie', 'gym-flex-beanie', 'Ribbed knit beanie with embroidered logo. One-size-fits-all stretch fit.', 699, NULL, 0, 1, 0, 19),
('gymflex-wrist-straps', 'mens', 'Leather Wrist Straps', 'leather-wrist-straps', 'Premium leather wrist straps for heavy lifting. Padded support with reinforced stitching.', 899, NULL, 0, 1, 0, 20)
ON CONFLICT(id) DO NOTHING;

INSERT INTO product_variants (id, product_id, type, name, sort_order, image_url) VALUES
('var-dri-fit-tee-1', 'gymflex-dri-fit-tee', 'Size', 'S', 0, ''),
('var-dri-fit-tee-2', 'gymflex-dri-fit-tee', 'Size', 'M', 1, ''),
('var-dri-fit-tee-3', 'gymflex-dri-fit-tee', 'Size', 'L', 2, ''),
('var-dri-fit-tee-4', 'gymflex-dri-fit-tee', 'Size', 'XL', 3, ''),
('var-compression-tank-1', 'gymflex-compression-tank', 'Size', 'S', 0, ''),
('var-compression-tank-2', 'gymflex-compression-tank', 'Size', 'M', 1, ''),
('var-compression-tank-3', 'gymflex-compression-tank', 'Size', 'L', 2, ''),
('var-compression-tank-4', 'gymflex-compression-tank', 'Size', 'XL', 3, ''),
('var-joggers-1', 'gymflex-joggers', 'Size', 'S', 0, ''),
('var-joggers-2', 'gymflex-joggers', 'Size', 'M', 1, ''),
('var-joggers-3', 'gymflex-joggers', 'Size', 'L', 2, ''),
('var-joggers-4', 'gymflex-joggers', 'Size', 'XL', 3, ''),
('var-stringer-1', 'gymflex-stringer', 'Size', 'S', 0, ''),
('var-stringer-2', 'gymflex-stringer', 'Size', 'M', 1, ''),
('var-stringer-3', 'gymflex-stringer', 'Size', 'L', 2, ''),
('var-stringer-4', 'gymflex-stringer', 'Size', 'XL', 3, ''),
('var-shorts-1', 'gymflex-shorts', 'Size', 'S', 0, ''),
('var-shorts-2', 'gymflex-shorts', 'Size', 'M', 1, ''),
('var-shorts-3', 'gymflex-shorts', 'Size', 'L', 2, ''),
('var-shorts-4', 'gymflex-shorts', 'Size', 'XL', 3, ''),
('var-hoodie-1', 'gymflex-hoodie', 'Size', 'S', 0, ''),
('var-hoodie-2', 'gymflex-hoodie', 'Size', 'M', 1, ''),
('var-hoodie-3', 'gymflex-hoodie', 'Size', 'L', 2, ''),
('var-hoodie-4', 'gymflex-hoodie', 'Size', 'XL', 3, ''),
('var-track-pants-1', 'gymflex-track-pants', 'Size', 'S', 0, ''),
('var-track-pants-2', 'gymflex-track-pants', 'Size', 'M', 1, ''),
('var-track-pants-3', 'gymflex-track-pants', 'Size', 'L', 2, ''),
('var-track-pants-4', 'gymflex-track-pants', 'Size', 'XL', 3, ''),
('var-singlet-1', 'gymflex-singlet', 'Size', 'S', 0, ''),
('var-singlet-2', 'gymflex-singlet', 'Size', 'M', 1, ''),
('var-singlet-3', 'gymflex-singlet', 'Size', 'L', 2, ''),
('var-singlet-4', 'gymflex-singlet', 'Size', 'XL', 3, ''),
('var-cargo-joggers-1', 'gymflex-cargo-joggers', 'Size', 'S', 0, ''),
('var-cargo-joggers-2', 'gymflex-cargo-joggers', 'Size', 'M', 1, ''),
('var-cargo-joggers-3', 'gymflex-cargo-joggers', 'Size', 'L', 2, ''),
('var-cargo-joggers-4', 'gymflex-cargo-joggers', 'Size', 'XL', 3, ''),
('var-racerback-1', 'gymflex-racerback', 'Size', 'S', 0, ''),
('var-racerback-2', 'gymflex-racerback', 'Size', 'M', 1, ''),
('var-racerback-3', 'gymflex-racerback', 'Size', 'L', 2, ''),
('var-racerback-4', 'gymflex-racerback', 'Size', 'XL', 3, ''),
('var-sleeveless-hoodie-1', 'gymflex-sleeveless-hoodie', 'Size', 'S', 0, ''),
('var-sleeveless-hoodie-2', 'gymflex-sleeveless-hoodie', 'Size', 'M', 1, ''),
('var-sleeveless-hoodie-3', 'gymflex-sleeveless-hoodie', 'Size', 'L', 2, ''),
('var-sleeveless-hoodie-4', 'gymflex-sleeveless-hoodie', 'Size', 'XL', 3, ''),
('var-thermal-tee-1', 'gymflex-thermal-tee', 'Size', 'S', 0, ''),
('var-thermal-tee-2', 'gymflex-thermal-tee', 'Size', 'M', 1, ''),
('var-thermal-tee-3', 'gymflex-thermal-tee', 'Size', 'L', 2, ''),
('var-thermal-tee-4', 'gymflex-thermal-tee', 'Size', 'XL', 3, ''),
('var-5inch-shorts-1', 'gymflex-5inch-shorts', 'Size', 'S', 0, ''),
('var-5inch-shorts-2', 'gymflex-5inch-shorts', 'Size', 'M', 1, ''),
('var-5inch-shorts-3', 'gymflex-5inch-shorts', 'Size', 'L', 2, ''),
('var-5inch-shorts-4', 'gymflex-5inch-shorts', 'Size', 'XL', 3, ''),
('var-zip-hoodie-1', 'gymflex-zip-hoodie', 'Size', 'S', 0, ''),
('var-zip-hoodie-2', 'gymflex-zip-hoodie', 'Size', 'M', 1, ''),
('var-zip-hoodie-3', 'gymflex-zip-hoodie', 'Size', 'L', 2, ''),
('var-zip-hoodie-4', 'gymflex-zip-hoodie', 'Size', 'XL', 3, ''),
('var-muscle-tee-1', 'gymflex-muscle-tee', 'Size', 'S', 0, ''),
('var-muscle-tee-2', 'gymflex-muscle-tee', 'Size', 'M', 1, ''),
('var-muscle-tee-3', 'gymflex-muscle-tee', 'Size', 'L', 2, ''),
('var-muscle-tee-4', 'gymflex-muscle-tee', 'Size', 'XL', 3, ''),
('var-compression-leggings-1', 'gymflex-compression-leggings', 'Size', 'S', 0, ''),
('var-compression-leggings-2', 'gymflex-compression-leggings', 'Size', 'M', 1, ''),
('var-compression-leggings-3', 'gymflex-compression-leggings', 'Size', 'L', 2, ''),
('var-compression-leggings-4', 'gymflex-compression-leggings', 'Size', 'XL', 3, ''),
('var-polo-1', 'gymflex-polo', 'Size', 'S', 0, ''),
('var-polo-2', 'gymflex-polo', 'Size', 'M', 1, ''),
('var-polo-3', 'gymflex-polo', 'Size', 'L', 2, ''),
('var-polo-4', 'gymflex-polo', 'Size', 'XL', 3, ''),
('var-tank-top-1', 'gymflex-tank-top', 'Size', 'S', 0, ''),
('var-tank-top-2', 'gymflex-tank-top', 'Size', 'M', 1, ''),
('var-tank-top-3', 'gymflex-tank-top', 'Size', 'L', 2, ''),
('var-tank-top-4', 'gymflex-tank-top', 'Size', 'XL', 3, ''),
('var-windbreaker-1', 'gymflex-windbreaker', 'Size', 'S', 0, ''),
('var-windbreaker-2', 'gymflex-windbreaker', 'Size', 'M', 1, ''),
('var-windbreaker-3', 'gymflex-windbreaker', 'Size', 'L', 2, ''),
('var-windbreaker-4', 'gymflex-windbreaker', 'Size', 'XL', 3, ''),
('var-beanie-1', 'gymflex-beanie', 'Size', 'One Size', 0, ''),
('var-wrist-straps-1', 'gymflex-wrist-straps', 'Size', 'One Size', 0, '')
ON CONFLICT(id) DO NOTHING;
