PRAGMA foreign_keys = OFF;

-- Reviews
INSERT OR IGNORE INTO reviews (id, product_id, rating, title, body, author_name, is_approved, created_at) VALUES
('rev-dri-fit-1', 'gymflex-dri-fit-tee', 5, 'Best tee for gym', 'Incredible fabric quality. Keeps me dry during heavy sessions. True to size.', 'Ali R.', 1, '2025-09-10'),
('rev-dri-fit-2', 'gymflex-dri-fit-tee', 4, 'Great value', 'Comfortable and breathable. The fit is slightly loose which I like.', 'Hassan M.', 1, '2025-10-05'),
('rev-dri-fit-3', 'gymflex-dri-fit-tee', 5, 'Recommend', 'Bought three of these. Wash well and dont shrink. Perfect for Lahore weather.', 'Usman K.', 1, '2025-11-12'),
('rev-dri-fit-4', 'gymflex-dri-fit-tee', 4, 'Good quality', 'Decent tee for the price. Logo is subtle which I appreciate.', 'Ahmed S.', 1, '2025-12-01'),
('rev-comp-tank-1', 'gymflex-compression-tank', 5, 'Perfect fit', 'Compression is just right. Not too tight, not too loose. Arm holes are perfectly sized.', 'Bilal A.', 1, '2025-08-15'),
('rev-comp-tank-2', 'gymflex-compression-tank', 4, 'Good tank', 'Nice material and stitching. Runs slightly small so size up.', 'Salman K.', 1, '2025-09-20'),
('rev-comp-tank-3', 'gymflex-compression-tank', 5, 'Love this', 'My go-to gym tank. The fabric is soft yet durable.', 'Taha R.', 1, '2025-10-10'),
('rev-comp-tank-4', 'gymflex-compression-tank', 3, 'Okay', 'Average quality. Stitching could be better around the neck.', 'Zain A.', 1, '2025-11-05'),
('rev-comp-tank-5', 'gymflex-compression-tank', 5, 'Excellent', 'Bought for my son and he loves it. Great quality GymFlex products!', 'Fatima A.', 1, '2025-12-15'),
('rev-joggers-1', 'gymflex-joggers', 5, 'Perfect joggers', 'Finally found joggers that fit well. Tapered leg is ideal and the pockets are deep enough for phone.', 'Omar F.', 1, '2025-09-01'),
('rev-joggers-2', 'gymflex-joggers', 4, 'Very comfortable', 'Soft inside and look great. Zip pockets are a nice touch.', 'Hammad N.', 1, '2025-10-18'),
('rev-joggers-3', 'gymflex-joggers', 5, 'Get these', 'Worth every rupee. Wore them to gym and casual outings both.', 'Saad M.', 1, '2025-11-22'),
('rev-joggers-4', 'gymflex-joggers', 4, 'Nice quality', 'Good stitching and material. Sizing is accurate.', 'Rayan A.', 1, '2025-12-10'),
('rev-stringer-1', 'gymflex-stringer', 5, 'Classic stringer', 'Perfect for shoulder day. Full range of motion and looks great.', 'Haroon S.', 1, '2025-08-28'),
('rev-stringer-2', 'gymflex-stringer', 4, 'Good cut', 'Nice deep armholes. Fabric is a bit thin but breathable.', 'Aamir K.', 1, '2025-09-15'),
('rev-stringer-3', 'gymflex-stringer', 3, 'Decent', 'Sizing runs small. Quality is okay for the price.', 'Naveed R.', 1, '2025-10-20'),
('rev-stringer-4', 'gymflex-stringer', 5, 'Love it', 'Best stringer I have owned. Will definitely buy more.', 'Fahad M.', 1, '2025-11-08'),
('rev-shorts-1', 'gymflex-shorts', 4, 'Great shorts', 'Lightweight and perfect for training. The phone pocket is a lifesaver.', 'Zubair A.', 1, '2025-09-05'),
('rev-shorts-2', 'gymflex-shorts', 5, 'Perfect length', '7 inch is the sweet spot. Enough coverage without restricting movement.', 'Saifullah K.', 1, '2025-10-12'),
('rev-shorts-3', 'gymflex-shorts', 4, 'Nice shorts', 'Comfortable for both gym and runs. Liner is well designed.', 'Waleed M.', 1, '2025-11-20'),
('rev-shorts-4', 'gymflex-shorts', 5, 'Buy these', 'Best training shorts I have used. Fabric quality is top notch.', 'Imran P.', 1, '2025-12-05'),
('rev-hoodie-1', 'gymflex-hoodie', 5, 'Cozy and stylish', 'Oversized fit is perfect. French terry fabric is soft and warm without being heavy.', 'Daniyal S.', 1, '2025-09-20'),
('rev-hoodie-2', 'gymflex-hoodie', 5, 'Amazing hoodie', 'Got compliments at the gym. Great quality and stitching.', 'Rohail A.', 1, '2025-10-15'),
('rev-hoodie-3', 'gymflex-hoodie', 4, 'Good hoodie', 'Nice and warm. Slightly oversized as expected. Good for Lahore winters.', 'Hamza B.', 1, '2025-11-01'),
('rev-hoodie-4', 'gymflex-hoodie', 4, 'Recommended', 'Quality fabric and well made. Only the pockets could be deeper.', 'Shehryar K.', 1, '2025-12-10'),
('rev-hoodie-5', 'gymflex-hoodie', 5, 'Perfect', 'Best purchase this month. My new favorite hoodie.', 'Ahmad R.', 1, '2026-01-05'),
('rev-w-leggings-1', 'gymflex-women-leggings', 5, 'Squat proof!', 'These leggings are amazing. Completely squat proof and super comfortable.', 'Ayesha K.', 1, '2025-09-15'),
('rev-w-leggings-2', 'gymflex-women-leggings', 5, 'Love the fit', 'High waist stays in place during workouts. Fabric is buttery soft.', 'Fatima Z.', 1, '2025-10-20'),
('rev-w-leggings-3', 'gymflex-women-leggings', 4, 'Very good', 'Great quality and true to size. Wish they came in more colors.', 'Zara H.', 1, '2025-11-08'),
('rev-w-leggings-4', 'gymflex-women-leggings', 5, 'Best leggings', 'Bought two pairs. Worth every penny for the quality.', 'Sana M.', 1, '2025-12-01'),
('rev-w-leggings-5', 'gymflex-women-leggings', 4, 'Good but pricey', 'Quality is excellent. Slightly expensive but you get what you pay for.', 'Mahnoor A.', 1, '2026-01-10'),
('rev-w-bra-1', 'gymflex-women-sports-bra', 5, 'Great support', 'Medium support is perfect for gym and cardio. Very comfortable for extended wear.', 'Hira N.', 1, '2025-09-25'),
('rev-w-bra-2', 'gymflex-women-sports-bra', 4, 'Nice bra', 'Good fit and padding is removable. Straps are adjustable which is great.', 'Mariam S.', 1, '2025-10-30'),
('rev-w-bra-3', 'gymflex-women-sports-bra', 5, 'Love it', 'Racerback design is cute and functional. Color options are lovely.', 'Rabia K.', 1, '2025-11-15'),
('rev-w-bra-4', 'gymflex-women-sports-bra', 4, 'Comfortable', 'Good for medium intensity workouts. Would buy again.', 'Sadia T.', 1, '2025-12-20'),
('rev-bottle-1', 'gymflex-water-bottle', 5, 'Keeps water cold', 'Ice water stays cold for a full day. No condensation on the outside. Perfect gym companion.', 'Zain A.', 1, '2025-10-05'),
('rev-bottle-2', 'gymflex-water-bottle', 4, 'Good bottle', 'Sturdy build and nice design. The spout could be a bit wider for cleaning.', 'Ali H.', 1, '2025-11-10'),
('rev-bottle-3', 'gymflex-water-bottle', 5, 'Worth it', '750ml is the perfect size. Fits in most cup holders and gym bag pockets.', 'Omer K.', 1, '2025-12-15'),
('rev-racerback-1', 'gymflex-racerback', 5, 'Great mobility', 'Racerback design gives full shoulder freedom. Very breathable fabric.', 'Faisal R.', 1, '2025-10-10'),
('rev-racerback-2', 'gymflex-racerback', 4, 'Nice tee', 'Good quality and fit. Anti-odor tech actually works.', 'Taimoor S.', 1, '2025-11-15'),
('rev-racerback-3', 'gymflex-racerback', 5, 'Perfect', 'My new favorite gym tee. Bought two more after trying the first one.', 'Waqar Z.', 1, '2025-12-20'),
('rev-straps-1', 'gymflex-lifting-straps', 5, 'Solid straps', 'Great for heavy deadlifts. Padding prevents wrist pain even at 150kg+.', 'Arslan M.', 1, '2025-10-15'),
('rev-straps-2', 'gymflex-lifting-straps', 4, 'Good quality', 'Neoprene padding is comfortable. 60cm length is sufficient for most wraps.', 'Bilal R.', 1, '2025-11-20'),
('rev-straps-3', 'gymflex-lifting-straps', 5, 'Highly recommend', 'Best straps I have used. Stitching is reinforced and they feel durable.', 'Hassan A.', 1, '2025-12-25'),
('rev-bag-1', 'gymflex-gym-bag', 5, 'Perfect gym bag', 'Spacious with great organization. Wet pocket is a game changer for post-swim gym sessions.', 'Saad K.', 1, '2025-11-01'),
('rev-bag-2', 'gymflex-gym-bag', 4, 'Good bag', 'Lots of compartments. Could use a bit more padding on the shoulder strap.', 'Usman G.', 1, '2025-12-05'),
('rev-bag-3', 'gymflex-gym-bag', 5, 'Excellent quality', 'Waterproof material works as advertised. Shoe compartment keeps everything separate.', 'Hamza N.', 1, '2026-01-10'),
('rev-knee-1', 'gymflex-knee-sleeves', 5, 'Great for squats', 'Adds confidence on heavy squats. Keeps knees warm between sets.', 'Shahmir A.', 1, '2025-10-20'),
('rev-knee-2', 'gymflex-knee-sleeves', 4, 'Good support', '7mm is thick but manageable. Follow the sizing chart carefully.', 'Awais M.', 1, '2025-11-25'),
('rev-w-hoodie-1', 'gymflex-women-hoodie', 5, 'Super cozy', 'Oversized fit is perfect for lounging and light gym wear. Amazing fabric.', 'Hira N.', 1, '2025-10-25'),
('rev-w-hoodie-2', 'gymflex-women-hoodie', 4, 'Nice hoodie', 'Warm and comfortable. Great for Islamabad winters.', 'Sana M.', 1, '2025-12-01'),
('rev-w-tank-1', 'gymflex-women-tank', 5, 'Cute and comfy', 'Cropped length is perfect. Looks great with high-waist leggings.', 'Mariam S.', 1, '2025-10-28'),
('rev-w-tank-2', 'gymflex-women-tank', 4, 'Nice fit', 'Flattering cut and good quality material. Would love more colors.', 'Zara H.', 1, '2025-11-30'),
('rev-bands-1', 'gymflex-resistance-bands', 5, 'Great set', '5 bands cover all resistance levels. Bag makes it easy to carry to the gym.', 'Taha R.', 1, '2025-11-05'),
('rev-bands-2', 'gymflex-resistance-bands', 4, 'Good quality bands', 'Latex is thick and durable. The included exercise guide has useful routines.', 'Rayan A.', 1, '2025-12-15'),
('rev-5shorts-1', 'gymflex-5inch-shorts', 5, 'Best running shorts', 'Lightweight and breezy. Built-in brief is comfortable and supportive.', 'Ali R.', 1, '2025-11-08'),
('rev-5shorts-2', 'gymflex-5inch-shorts', 4, 'Nice shorts', 'Good for hot weather training. Side splits allow full leg movement.', 'Salman K.', 1, '2025-12-20'),
('rev-zip-1', 'gymflex-zip-hoodie', 5, 'Full zip is handy', 'Easy to layer on and off between sets. Thumbholes are a nice bonus.', 'Ahmed S.', 1, '2025-11-12'),
('rev-zip-2', 'gymflex-zip-hoodie', 4, 'Good quality', 'Stand up collar looks sharp. Zippered pockets keep phone secure.', 'Zain A.', 1, '2025-12-25'),
('rev-roller-1', 'gymflex-foam-roller', 5, 'Great for recovery', 'Medium density hits the sweet spot. Textured surface really works out knots.', 'Bilal A.', 1, '2025-11-15'),
('rev-roller-2', 'gymflex-foam-roller', 4, 'Solid roller', 'Good size for travel. Sturdy and doesnt lose shape.', 'Omar F.', 1, '2025-12-28');

PRAGMA foreign_keys = ON;
