name = "gymflex-admin"
pages_build_output_dir = "dist"
compatibility_date = "2026-06-22"

[[kv_namespaces]]
binding = "STORE_KV"
id = "03a00ee02243453f8b4824fdf53f5505"

[[d1_databases]]
binding = "STORE_DB"
database_name = "gymflex_d1"
database_id = "c51412b2-c1a5-4201-bf9a-a0f4d961e6eb"

[[r2_buckets]]
binding = "STORE_BUCKET"
bucket_name = "gymflex-r2"
